spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: service-a
  profiles:
    active: dev

logging:
  level:
    org.springframework.cloud.context.config: TRACE
    org.springframework.beans: DEBUG

server:
  port: 8090
